name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Decrypt the keystore
      run: gpg --quiet --batch --yes --decrypt --passphrase='${{ secrets.KEYSTORE_DECRYPT_PASSWORD }}' --output sample-key.keystore sample-key.keystore.gpg

    - name: Decrypt the keystore properties
      run: gpg --quiet --batch --yes --decrypt --passphrase='${{ secrets.KEYSTORE_PROPERTIES_DECRYPT_PASSWORD }}' --output sample-keystore.properties sample-keystore.properties.gpg

    - name: Build with Gradle
      run: ./gradlew assembleRelease

    - uses: actions/upload-artifact@v4
      with:
        name: all-apks
        path: app/build/outputs/apk/**/release/*.apk

    # - name: Package into one file
    #   run: find . -name "*.apk" -exec zip -j apks.zip {} +


    # - name: Print sizes
    #   working-directory: ./app/build/outputs/apk/
    #   run: find . -name '*.apk' | while read line; do; ls -lh "$line" |  awk '{gsub(/\.\/app\/build\/outputs\/apk\//,"",$9);gsub(/.*release\/app-[0-9][0-9]-/,"",$9);gsub(/-release-unsigned\.apk/,"",$9);gsub(/0-without-sdk\/release\/app-0-/,"",$9);print}' | awk '{print $5, $9}' >> $GITHUB_STEP_SUMMARY ; done



  list-sizes:
    runs-on: ubuntu-latest
    needs: build
    steps:

    - name: Download a single artifact
      uses: actions/download-artifact@v4
      with:
        name: all-apks

    - name: List files
        run: find .

    - name: List file sizes
      shell: bash
      run: |
        find . -name '*.apk' | while read line; do; ls -lh "$line" |  awk '{gsub(/\.\/app\/build\/outputs\/apk\//,"",$9);gsub(/.*release\/app-[0-9][0-9]-/,"",$9);gsub(/-release-unsigned\.apk/,"",$9);gsub(/0-without-sdk\/release\/app-0-/,"",$9);print}' | awk '{print $5, $9}' ; done


