name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Decrypt the keystore
      run: gpg --quiet --batch --yes --decrypt --passphrase='${{ secrets.KEYSTORE_DECRYPT_PASSWORD }}' --output app/sample-key.keystore sample-key.keystore.gpg

    - name: Decrypt the keystore properties
      run: gpg --quiet --batch --yes --decrypt --passphrase='${{ secrets.KEYSTORE_PROPERTIES_DECRYPT_PASSWORD }}' --output app/sample-keystore.properties sample-keystore.properties.gpg

    - name: Collect Branch Name from gradle.properties into env
      run: echo "BRANCH_COMPLETE_NAME=size-docs-for-android-sdk-$(./gradlew -q branchSuffixForDocsPR)" >> $GITHUB_ENV

    - name: Build with Gradle
      run: ./gradlew assembleRelease

    # - name: Check file size 
    #   run: zipinfo app/build/outputs/apk/02-android-sdk/release/

    - name: Archive code coverage results
      uses: actions/upload-artifact@v4
      with:
        name: apks
        path: app/build/outputs/apk/02-android-sdk/release/*

